config/routes.rb
Rails.application.routes.draw do
  resources :bulk_transactions do
  member do
    get :addpayment
  end
end
  resources :payments
  resources :donations
  resources :scholarships
  resources :students
  resources :sponsors

  root 'sponsors#index'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/create_payments', to: "payments#create_payments"  
  get 'listings/submit_sponsor', as: 'submit_sponsor'
  
  get 'sponsors/:id/send_email', to: "sponsors#send_email", as: 'sponsor_send_email'
  
  get '/fye_report', to: 'sponsors#fye_report'
  

end

app/models/student.rb
class Student < ActiveRecord::Base
  has_many :scholarships
  has_many :payments
  has_many :student_feedback
  
  DEPARTMENTS = ['CSE', 'ENTC', 'MEC']
  FACULTIES = ['ENG', 'TCP']

  def full_name
    "#{first_name} #{last_name}"
  end
  
  def external_name
    "#{first_name} #{last_name[0,1]}."
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    respond_to do |format|
          format.html
          format.pdf do
            pdf = StudentReportPdf.new(@student)
            send_data pdf.render, filename: @student.full_name+'.pdf', type: 'application/pdf'
        #SponsorReportMailer.send_report(@sponsor).deliver_later
          end
    end
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_student
      @student = Student.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def student_params
      params.require(:student).permit(:first_name, :last_name, :email, :phone, :address, :faculty, :department)
    end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>
  <% if @student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name , class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :address %><br>
    <%= f.text_area :address, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :faculty %><br>
    <%= f.text_field :faculty, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department, class:"form-control", :required => true %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student%> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>
<%= link_to 'New Student', new_student_path, class: "btn btn-primary"  %>
<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Faculty</th>
      <th>Department</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.order(id: :desc).each do |student| %>
      <tr>
        <td><%= link_to student.full_name, student_path(student)%></td>
        <td><%= student.email %></td>
        <td><%= student.phone %></td>
        <td><%= student.address %></td>
        <td><%= student.faculty %></td>
        <td><%= student.department %></td>
        <td><%= link_to 'View', student_path(student,format: 'pdf'), class: "btn btn-info glyphicon glyphicon-info-sign" %></td>
        <td><%= link_to 'Edit', edit_student_path(student), class: "btn btn-warning glyphicon glyphicon-edit" %></td>
        <td><%= link_to 'Delete', student, method: :delete, data: { confirm: 'Are you sure?'} , class: "btn btn-danger glyphicon glyphicon-remove" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path, class: "btn btn-primary"  %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice" class=bg-success"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @student.first_name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @student.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @student.email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>

<p>
  <strong>Faculty:</strong>
  <%= @student.faculty %>
</p>

<p>
  <strong>Department:</strong>
  <%= @student.department %>
</p>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Scholarships</h4> </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
       <tr>
       <th>Scholarship Id </th>
        <th>Sponsor</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Amount (Rs.)</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <% @student.scholarships.sort_by{|x| x.start_date}.each do |schol| %>
        <tr>
          <td><%=link_to schol do%><%=schol.id %><% end %></td>
          <td><%= link_to schol.sponsor do%>  <%= schol.sponsor.full_name %> <% end %></td>
          <td><%= schol.start_date %></td>
          <td><%= schol.end_date %></td>
          <td><%= number_to_currency(schol.amount , unit:"Rs.", precision: 2)%></td>
          <td><%= schol.status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<% @student.scholarships.sort_by{|x| x.start_date}.reverse.each do |schol| %>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Payments made to student for scholarship : <%=link_to schol do%><%=schol.id %><% end %> </h4></div>
  <%= render partial: "payments/payment", locals: {pp:schol.past_payments} %>
</div>
<% end %>

<% if @student.student_feedback.any? %>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Student feedback</h4> </div>
  <div class="panel-body">
  <table class="table table-striped">
  <% @student.student_feedback.sort_by{|x| x.timestamp}.each do |fb| %>
  <tr><th><%=localize(fb.timestamp,:format => :long) %> - Renew Year : <%=fb.renew_year%></th></tr>
  <tr><td>
  <b>Academic Progress: </b><br/>
  <%=fb.academic_progress.gsub('\n', '<br/>').html_safe %>
  
  <br/><b>Notes:</b> <br/>
  <%=fb.comments.gsub('\n','<br/>').html_safe %>
  </td></tr>
  <% end %>
    </table>
  </div>
<% end %>
</div>


<%= link_to 'Edit', edit_student_path(@student), class: "btn btn-warning" %> |
<%= link_to 'Back', students_path %>