config/routes.rb
Rails.application.routes.draw do
  resources :bulk_transactions do
  member do
    get :addpayment
  end
end
  resources :payments
  resources :donations
  resources :scholarships
  resources :students
  resources :sponsors

  root 'sponsors#index'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/create_payments', to: "payments#create_payments"  
  get 'listings/submit_sponsor', as: 'submit_sponsor'
  
  get 'sponsors/:id/send_email', to: "sponsors#send_email", as: 'sponsor_send_email'
  
  get '/fye_report', to: 'sponsors#fye_report'
  

end

app/views/shared/_menu.html.erb
<header class="navbar  navbar-inverse">
  <div class="navbar-class">
    <div class="container">
      <ul class="nav navbar-nav">
        <li> <%= image_tag("logo.png", :alt => "rss feed") %></li>
        <% if current_user %>
        <li><%=link_to "Sponsors", sponsors_path%></li>
        <li><%=link_to "Students", students_path%></li>
        <li><%=link_to "Scholarships", scholarships_path%></li>
        <li><%=link_to "Donations", donations_path%></li>
        <li><%=link_to "Payments", payments_path%></li>
        <li><%=link_to "Bulk Transactions", bulk_transactions_path%></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li class="nav navbar-nav pull-right"><%= image_tag current_user.image_url, alt: current_user.name %></li>
        <li class="nav navbar-nav pull-right"><%= link_to 'Log Out', logout_path, method: :delete %></li>
      <% else %>
        <!--<li><%=link_to 'Twitter', '/auth/twitter' %></li>-->
          <li><%= link_to 'Google+', '/auth/google' %></li>
      <% end %>
      </ul>
    </div>
  </div>
</header>