config/routes.rb
Rails.application.routes.draw do
  resources :bulk_transactions do
  member do
    get :addpayment
  end
end
  resources :payments
  resources :donations
  resources :scholarships
  resources :students
  resources :sponsors

  root 'sponsors#index'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/create_payments', to: "payments#create_payments"  
  get 'listings/submit_sponsor', as: 'submit_sponsor'
  
  get 'sponsors/:id/send_email', to: "sponsors#send_email", as: 'sponsor_send_email'
  
  get '/fye_report', to: 'sponsors#fye_report'
  

end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
  has_many :scholarships
  has_many :donations
  has_many :bad_debts
  
  TITLES =  ['Mr.', 'Mrs.', 'Ms.', 'Dr.']

    
  def full_name
    "#{first_name} #{last_name}"
  end

  def active_schols_count
    count =0
    self.scholarships.each do |schol|
          if (schol.status=='ACTIVE')
            count+=1
          end
        end
    count
  end
  
  def scholarship_start_year
    firstScholStart = nil
    self.scholarships.each do |schol|
      if (firstScholStart==nil or firstScholStart>schol.start_date.year)
        firstScholStart=schol.start_date.year
      end
    end
    firstScholStart
  end
  
  def total_donations
    total = 0
    self.donations.each do |donation|
      total += donation.amount
    end
    total
  end

  def total_scholarship_amount
    total = 0
    self.scholarships.each do |schol|
      total += schol.amount * ((Date.today.year * 12 + Date.today.month) - (schol.start_date.year * 12 + schol.start_date.month))
    end
    total
  end

  
  def total_payments_aud
    total = 0
    self.scholarships.each do |schol|
      schol.payments.each do |p|
        total += p.amount_aud
      end
    end
    total
   end
  
  def total_payments_lkr
    total = 0
    self.scholarships.each do |schol|
      schol.payments.each do |p|
          total += p.amount
        end
    end
        total
    end
    
    
  def total_payments_aud_before_FYE(fye)
    total = 0
    self.scholarships.each do |schol|
      schol.payments.each do |p|
        if (p.effective_year<fye or (p.effective_year==fye and ['1.0','2.0','3.0','4.0','5.0','6.0'].include?p.effective_month))
          total += p.amount_aud
        end
      end
    end
    total
   end
   
  def total_payments_aud_within_FYE(fye)
    total = 0
    self.scholarships.each do |schol|
      schol.payments.each do |p|
        if ((p.effective_year==  (fye+1) and ['1.0','2.0','3.0','4.0','5.0','6.0'].include?p.effective_month) or (p.effective_year==fye and ['7.0','8.0','9.0','10.0','11.0','12.0'].include?p.effective_month))
          total += p.amount_aud
        end
      end
    end
    total
   end

  def total_bad_debts_at(eff_date)
    total = 0
    self.bad_debts.each do |debt|
      if (debt.eff_date<= eff_date)
        total += debt.amount
      end
      
    end
    total
  end

     
   def total_donations_before_FYE(fye)
     total = 0
     self.donations.each do |donation|
       if (donation.bank_date< Date.new(fye,7,1))
         total += donation.amount
       end
       
     end
     total
   end

  def total_donations_within_FYE(fye)
    total = 0
    self.donations.each do |donation|
      if (donation.bank_date>= Date.new(fye,7,1) and donation.bank_date< Date.new(fye+1,7,1))
        total += donation.amount
      end
      
    end
    total
  end

  def get_balance_due()
    badDebt=self.total_bad_debts_at(Date.today)
    balanceDue= self.total_donations + badDebt - self.total_payments_aud
    balanceDue
  end
       
  # def outstanding
  #   to_pay = 0
  #   current_aud_lkr = 100
  #
  #   self.scholarships.each do |schol|
  #     to_pay += schol.amount * ((Date.today.year * 12 + Date.today.month) - (schol.start_date.year * 12 + schol.start_date.month))
  #   end
  #
  #   self.donations.each do |donation|
  #     to_pay -= donation.amount * current_aud_lkr
  #   end
  #
  #   to_pay
  # end
end

app/controllers/sponsors_controller.rb
class SponsorsController < ApplicationController
  before_action :set_sponsor, only: [:show, :edit, :update, :destroy, :send_email]

  # GET /sponsors
  # GET /sponsors.json
  def index
    @sponsors = Sponsor.all
  end

  # GET /sponsors
  # GET /sponsors.json
  def fye_report
    @sponsors = Sponsor.all
  end
  
  # GET /sponsors/1
  # GET /sponsors/1.json
  def send_email
    istest=params[:istest]
    
   if (istest == 'true')
     SponsorReportMailer.send_report(@sponsor, session[:user_email]).deliver_later
     redirect_to sponsors_path, notice: 'Test Email sent to sponsor :'+@sponsor.full_name 
   else
     SponsorReportMailer.send_report(@sponsor, nil).deliver_later
     redirect_to sponsors_path, notice: 'Email sent to sponsor :'+@sponsor.full_name 
   end
  end
  
  # GET /sponsors/1
  # GET /sponsors/1.json
  def show
    respond_to do |format|
      format.html
      format.pdf do
        pdf = SponsorReportPdf.new(@sponsor)
        send_data pdf.render, filename: @sponsor.full_name+'.pdf', type: 'application/pdf'

      end
    end
  end

  # GET /sponsors/new
  def new
    @sponsor = Sponsor.new
  end

  # GET /sponsors/1/edit
  def edit
    #@sponsors = Sponsor.all
    #@sponsors.each do |sponsor|
    #  SponsorReportMailer.send_report(sponsor).deliver_later
    #  logger.info "Email sent for user #{sponsor.full_name}"
    #  end
  end

  # POST /sponsors
  # POST /sponsors.json
  def create
    @sponsor = Sponsor.new(sponsor_params)

    respond_to do |format|
      if @sponsor.save
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully created.' }
        format.json { render :show, status: :created, location: @sponsor }
      else
        format.html { render :new }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sponsors/1
  # PATCH/PUT /sponsors/1.json
  def update
    respond_to do |format|
      if @sponsor.update(sponsor_params)
        format.html { redirect_to @sponsor, notice: 'Sponsor was successfully updated.' }
        format.json { render :show, status: :ok, location: @sponsor }
      else
        format.html { render :edit }
        format.json { render json: @sponsor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sponsors/1
  # DELETE /sponsors/1.json
  def destroy
    @sponsor.destroy
    respond_to do |format|
      format.html { redirect_to sponsors_url, notice: 'Sponsor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sponsor
      @sponsor = Sponsor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sponsor_params
      params.require(:sponsor).permit(:title, :first_name, :last_name, :email, :phone)
    end
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
	
end

app/views/sponsors/_form.html.erb
<%= form_for(@sponsor) do |f| %>
  <% if @sponsor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sponsor.errors.count, "error") %> prohibited this sponsor from being saved:</h2>

      <ul>
        <% @sponsor.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :title %><br>
    <%= f.select :title, options_for_select(Sponsor::TITLES.map {|v| [ v, v]}, @sponsor.title), {}, {:class=>"form-control", :required => true} %>
  </div>
  <div class="field">
    <%= f.label :first_name %><br>
    <%= f.text_field :first_name, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br>
    <%= f.text_field :last_name, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email, class:"form-control", :required => true %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone, class:"form-control" %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/sponsors/edit.html.erb
<h1>Editing Sponsor</h1>

<%= render 'form' %>

<%= link_to 'Show', @sponsor  %> |
<%= link_to 'Back', sponsors_path %>

app/views/sponsors/fye_report.html.erb
<p id="notice"><%= notice %></p>

<% fye=2022
	cur_date = Date.today 
%>

<h1>Sponsors Summary  <%=fye %>-<%=fye+1 %> FYE</h1>
<%= link_to 'New Sponsor', new_sponsor_path, class: "btn btn-primary"  %> <br/>

<%= link_to 'Back', sponsors_path %>

<table class="table table-striped">
	
  <thead>
    <tr>
      <th>Name</th>
      
      <th>ScholPayments @<%=fye %>0630</th>
      <th>Donations @<%=fye %>0630</th>
      <th>Bad Debt@ <%=fye %>0630</th>
      <th>Accrued @ <%=fye %>0701</th>
      <th>Schols <%=fye %>-<%=fye+1 %>FYE</th>
      <th>Donations <%=fye %>-<%=fye+1 %>FYE</th>
      <th>Bad Debt@ <%=fye+1 %>0630</th>
      <th>Prepaid/Accrued @ <%=fye+1%>0630</th>
      <th>Prepaid/Arrears @ <%= cur_date.to_s %></th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.sort_by{|x| x.id}.each do |sponsor| %>
      <tr>
       <td><%= link_to sponsor do ('[' + sponsor.id.to_s + '] ' + sponsor.title + ' ' + sponsor.full_name) end %></td>
        <% 
        	paymentsSOY=sponsor.total_payments_aud_before_FYE(fye)
        	donationsSOY=sponsor.total_donations_before_FYE(fye)
          bad_debts_SOY = sponsor.total_bad_debts_at(Date.new(fye,6,30))
          accruedSOY=(donationsSOY + bad_debts_SOY) - paymentsSOY
        	paymentsFYE=sponsor.total_payments_aud_within_FYE(fye)
        	donationsFYE=sponsor.total_donations_within_FYE(fye)
        	bad_debts = sponsor.total_bad_debts_at(Date.new(fye+1,6,30))
        	debt = (donationsFYE + donationsSOY + bad_debts) - (paymentsSOY + paymentsFYE) 
        %>
        
        <td><%= number_to_currency(paymentsSOY) %></td>
        <td><%= number_to_currency(donationsSOY) %></td>
        <td><%= bad_debts_SOY %> </td>
        <td><%= number_to_currency(accruedSOY) %></td>

		<td><%= number_to_currency(paymentsFYE) %></td>
        <td><%= number_to_currency(donationsFYE) %></td>
        <td><%= bad_debts %> </td>
        <td><%if (debt < -0.01) %> 
        		<span class="text-danger">
        	<% else %>
        		<span class="text-info">
        	<% end %> 
        	<%= number_to_currency(debt, precision: 2)%>
        </span></td>
        <% gap = sponsor.total_donations + bad_debts - sponsor.total_payments_aud %>
        <td><%if (gap < -0.01) %> 
        		<span class="text-danger">
        	<% else %>
        		<span class="text-info">
        	<% end %> 
        	<%= number_to_currency(gap, precision: 2)%>
        </span></td>
        
        <td><%= link_to 'TestEMail', sponsor_send_email_path(sponsor, istest: true), class: "btn btn-info", title: "Mail only to "+ session[:user_email]%></td>
        <td><%= link_to 'EMail', sponsor_send_email_path(sponsor, istest: false), class: "btn btn-info", title: "Mail to sponsor CC'ing scholarships"%></td>
      </tr>
    <% end %>
  	</tbody>
</table>

<br/>
<br/>

app/views/sponsors/index.html.erb
<p id="notice"><%= notice %></p>
<%
if (session[:user_email] == nil)
	session[:user_email] ='indikamee@gmail.com' 
end
%>
<h1>Sponsors</h1>
<%= link_to 'New Sponsor', new_sponsor_path, class: "btn btn-primary"  %>
<%= link_to 'FYE Report 22-23', fye_report_path, class: "btn btn-primary"  %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Name</th>
      <th>#Scholarships</th>
      <th>#Active</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Prepaid/Arrears</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sponsors.sort_by{|x| x.id}.each do |sponsor| %>
      <tr>
        <td><%= sponsor.title %></td>
        <td><%= link_to sponsor do sponsor.full_name  end %></td>
        <td><%= sponsor.scholarships.count.to_s %></td>
        <td><%= sponsor.active_schols_count.to_s %></td>
        <td><%= sponsor.email %></td>
        <td><%= sponsor.phone %></td>
        <% bad_debts = sponsor.total_bad_debts_at(Date.today)
        	gap =sponsor.total_donations + bad_debts -sponsor.total_payments_aud %>
        <td><%if (gap < -0.01) %> 
        		<span class="text-danger">
        	<% else %>
        		<span class="text-info">
        	<% end %> 
        	<%= number_to_currency(gap, precision: 2)%>
        	</span></td>
        <td><%= link_to 'PDF', sponsor_path(sponsor,format: 'pdf') , class: "btn btn-success"%></td>
        <td><%= link_to 'TestEMail', sponsor_send_email_path(sponsor, istest: true), class: "btn btn-info", title: "Mail only to " + session[:user_email] %></td>
        <td><%= link_to 'EMail', sponsor_send_email_path(sponsor, istest: false), class: "btn btn-info", title: "Mail to sponsor CC'ing scholarships"%></td>
        <td><%= link_to 'Edit', edit_sponsor_path(sponsor),  class: "btn btn-warning" %></td>
        <td><%= link_to 'Delete', sponsor, method: :delete, data: { confirm: 'Are you sure?' },  class: "btn btn-danger"%></td>
      </tr>
    <% end %>
  	</tbody>
</table>

<br/>
<br/>

app/views/sponsors/new.html.erb
<h1>New Sponsor</h1>

<%= render 'form' %>

<%= link_to 'Back', sponsors_path %>

app/views/sponsors/show.html.erb
<p id="notice"><%= notice %></p>
<%= link_to 'Back', sponsors_path %>
<h1><%= @sponsor.title %> <%= @sponsor.first_name %>  <%= @sponsor.last_name %></h1>
<p> <small>E:  <%= @sponsor.email %> <br/> T:  <%= @sponsor.phone %></small></p>

<div class="text-right">
  <p>Total payments to your scholarships :<span class="text-info"> <%= number_to_currency(@sponsor.total_payments_lkr, unit: "Rs.", precision: 2) %></span></p>
  <p>Total value of payments in AUD:<span class="text-info"> <%= number_to_currency(@sponsor.total_payments_aud, precision: 2) %></span></p>
  
  <p>Contributions made by you:<span class="text-info"> <%= number_to_currency(@sponsor.total_donations, precision: 2) %></span></p>
  <p>Compensations by UMAAV :<span class="text-info"> <%= number_to_currency(@sponsor.total_bad_debts_at(Date.today), precision: 2) %></span></p>
</div>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Your Sponsorships</h4> </div>
  <div class="panel-body">
    <table class="table table-striped">
      <thead>
       <tr>
        <th>Student</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Faculty</th>
        <th>Amount (Rs.)</th>
        <th>Status</th>
      </tr>
      </thead>
      <tbody>
      <% @sponsor.scholarships.sort_by{|x| x.start_date}.reverse.each do |schol| %>
        <tr>
          <td><%= link_to schol.student do%>  <%= schol.student.full_name %> <% end %></td>
          <td><%= schol.start_date %></td>
          <td><%= schol.end_date %></td>
          <td><%= schol.student.faculty %></td>
          <td><%= link_to schol do%>  <%= number_to_currency(schol.amount , unit:"Rs.", precision: 2)%> <% end %></td>
          <td><%= schol.status %></td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

<br/>

<% @sponsor.scholarships.sort_by{|x| x.start_date}.reverse.each do |schol| %>
<div class="panel panel-default">
  <div class="panel-heading"><h4>Summary of sponsorship : <%= link_to schol do schol.student.full_name end%></h4></div>
  <% nextDonationDue = schol.get_next_donation_due_date %>
  <% if (nextDonationDue < Date.today and nextDonationDue < schol.end_date and nextDonationDue.year > (Date.today.year - 3) ) %> 
  	<h4><span class="text-danger">Contributions due from <%=nextDonationDue%></span></h4>
  <% end %>
   <% totalAUD=0 %>
   <% totalLKR = 0 %>  
  <table class="table table-striped">
      <thead>
 	  <tr><th class="bg-info" colspan=3> Scholarship payments made to the student:</th></tr>
      <tr>
        <th>Year</th>
        <th>Amount (Rs.)</th>
     	<th>Amount (AUD)</th>   
      </tr>
      </thead>

      <tbody>
      <% @pp = schol.payments.group(:effective_year).select('effective_year, sum(amount) as lkr, sum(amount_aud) as aud')%>

       <% @pp.sort_by{|x| x.effective_year}.each do |p| %>
        <tr>
          <td><%= p.effective_year %></td>
          <td><%= number_to_currency(p.lkr, precision: 2, unit: "Rs.")%></td>
          <td><%= number_to_currency(p.aud, precision: 2) %></td>
          <% totalAUD += p.aud %>
          <% totalLKR += p.lkr %>
        </tr>
      
      <% end %>
      	<tr>
      		<th>Total</th>
      		<th><%= number_to_currency(totalLKR, precision: 2, unit: "Rs.")%></th>
      		<th><%= number_to_currency(totalAUD, precision: 2)%></th>
      	</tr>
      </tbody>
	<tr></tr>
	<%totalDonations=0 %>
	  <thead>
	  <tr><th class="bg-info", colspan=3>Your contributions:</th></tr>
	  <tr>
	   	<th>Bank date</th>
	    <th>Allocated for</th>
	    <th>Amount (AUD) </th>
	  </tr>
	  </thead>
	  <tbody>
	      <% schol.donations.sort_by{|x| x.bank_date}.each do |donation| %>
	        <tr>
	          <td><%= link_to donation do%>  <%= donation.bank_date %> <% end %></td>	
	          
	          <!--td><%= link_to donation.scholarship do%> #<%= donation.scholarship.id %> for <%= donation.scholarship.student.full_name %> <% end %></td-->
	          <td><%= donation.num_of_months %> Months from <%= donation.valid_from %></td>
	          <td><%= number_to_currency (donation.amount) %></td>
			  <% totalDonations = totalDonations+donation.amount %>            
	        </tr>
	      <% end %>
	      <tr><th colspan=2>Total </th> <th><%= number_to_currency(totalDonations) %></th></tr>
		</tbody>
	</table>
	
</div>

<% end %>
<br/><br/>