config/routes.rb
Rails.application.routes.draw do
  resources :bulk_transactions do
  member do
    get :addpayment
  end
end
  resources :payments
  resources :donations
  resources :scholarships
  resources :students
  resources :sponsors

  root 'sponsors#index'

  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#create'

  post '/create_payments', to: "payments#create_payments"  
  get 'listings/submit_sponsor', as: 'submit_sponsor'
  
  get 'sponsors/:id/send_email', to: "sponsors#send_email", as: 'sponsor_send_email'
  
  get '/fye_report', to: 'sponsors#fye_report'
  

end

app/controllers/bulk_transactions_controller.rb
class BulkTransactionsController < ApplicationController
  before_action :set_bulk_transaction, only: [:show, :edit, :update, :destroy]
  helper_method :addpayment
  # GET /bulk_transactions
  # GET /bulk_transactions.json
  def index
    @bulk_transactions = BulkTransaction.all
  end

  # GET /bulk_transactions/1
  # GET /bulk_transactions/1.json
  def show
    
  end
  
  def addpayment
    @bulk_transaction = BulkTransaction.find(params[:id])
    @scholarships = Scholarship.where(status: "ACTIVE")
    @payment_details = []
    @scholarships.each do |schol|
       @payment_details.push (Payment_Details.new(schol, @bulk_transaction))
    end
  end
   
  
  # GET /bulk_transactions/new
  def new
    @bulk_transaction = BulkTransaction.new
  end

  # GET /bulk_transactions/1/edit
  def edit
  end

  # POST /bulk_transactions
  # POST /bulk_transactions.json
  def create
    @bulk_transaction = BulkTransaction.new(bulk_transaction_params)

    respond_to do |format|
      if @bulk_transaction.save
        format.html { redirect_to @bulk_transaction, notice: 'Bulk transaction was successfully created.' }
        format.json { render :show, status: :created, location: @bulk_transaction }
      else
        format.html { render :new }
        format.json { render json: @bulk_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bulk_transactions/1
  # PATCH/PUT /bulk_transactions/1.json
  def update
    respond_to do |format|
      if @bulk_transaction.update(bulk_transaction_params)
        format.html { redirect_to @bulk_transaction, notice: 'Bulk transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @bulk_transaction }
      else
        format.html { render :edit }
        format.json { render json: @bulk_transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bulk_transactions/1
  # DELETE /bulk_transactions/1.json
  def destroy
    @bulk_transaction.destroy
    respond_to do |format|
      format.html { redirect_to bulk_transactions_url, notice: 'Bulk transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bulk_transaction
      @bulk_transaction = BulkTransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bulk_transaction_params
      params.require(:bulk_transaction).permit(:settled_date, :sender, :amount, :amount_lkr, :rate, :bank_date, :chq_no, :bank_acc, :beneficiary, :notes, :effective_year, :effective_months)
    end
end

app/helpers/bulk_transactions_helper.rb
module BulkTransactionsHelper
end

app/views/bulk_transactions/_form.html.erb
<%= form_for(@bulk_transaction) do |f| %>
  <% if @bulk_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bulk_transaction.errors.count, "error") %> prohibited this bulk_transaction from being
        saved:</h2>

      <ul>
        <% @bulk_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="container-fluid">
    <div class="panel panel-default">
      <div class="panel-body">
          <div class="row">
            <div class="col-md-2 form-group">
              <%= f.label :amount %>
              <span class="input-group">
              <span class="input-group-addon">$</span><%= f.number_field :amount, class: "form-control currency rate_calc", :required => true, :id => "amount",step: :any %>
              </span>
            </div>
            <div class="col-md-2 form-group">
              (x) <%= f.label :rate%>
              <%= f.number_field :rate, class: "form-control rate_calc", :id => "aud_lkr_rate",step: :any %>
            </div>
            <div class="col-md-2" >
            </div>
            <div class="col-md-3 form-group">
              <%= f.label :"(=)"%>
              <span class="input-group">
              <span class="input-group-addon">Rs</span><%= f.text_field :amount_lkr, class: "form-control currency", :id => "amount_lkr" %>
            </span>
            </div>
          </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-5 form-group">
        <%= f.label :sender %>
        <%= f.text_field :sender, class: "form-control" %>
      </div>
      <div class="col-md-5 form-group">
        <%= f.label :beneficiary %>
        <%= f.text_field :beneficiary, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-3 form-group">
        <%= f.label :"Cheque number" %><br>
        <%= f.text_field :chq_no , class: "form-control"%>
      </div>
      <div class="col-md-3 form-group">
        <%= f.label :"Bank Account" %><br>
        <%= f.text_field :bank_acc, class: "form-control" %>
      </div>
      <div class="col-md-3 form-group">
        <%= f.label :bank_date %><br>
        <%= f.date_select :bank_date %>
      </div>
      <div class="col-md-3 form-group">
        <%= f.label :settled_date %><br>
        <%= f.date_select :settled_date %>
      </div>
    </div>

    <div class="row">
      <div class="col-md-2 form-group">
        <%= f.label :effective_year %><br>
        <%= f.number_field :effective_year, class: "form-control" %>
      </div>
      <div class="col-md-2 form-group">
        <%= f.label :effective_months %><br>
        <%= f.text_field :effective_months, class: "form-control" %>
      </div>
      <div class="col-md-8 form-group">
        <%= f.label :notes %><br>
        <%= f.text_area :notes, class: "form-control" %>
      </div>
    </div>

    <div class="actions">
      <%= f.submit class: "btn btn-primary"%>
    </div>

  </div>


<% end %>

app/views/bulk_transactions/addpayment.html.erb
<h1>Add payments to bulk transaction</h1>
<%= form_for(@bulk_transaction , :url => create_payments_path, :method => :POST) do |f| %>
  <% if @bulk_transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@bulk_transaction.errors.count, "error") %> prohibited this bulk_transaction from being
        saved:</h2>

      <ul>
        <% @bulk_transaction.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="panel-body">
    <table class="table table-striped">
      <thead>
       
       <tr><th>Settled date</th><td><%= @bulk_transaction.settled_date %></td></tr>
       <tr><th>Sender</th><td><%= @bulk_transaction.sender %></td></tr>
       <tr><th>Amount</th><td><%= @bulk_transaction.amount %></td></tr>
       <tr><th>Amount lkr</th><td><%= @bulk_transaction.amount_lkr %></td></tr>
       <tr><th>Rate</th><td><%= @bulk_transaction.rate %></td></tr>
       <tr><th>Bank date</th><td><%= @bulk_transaction.bank_date %></td></tr>
       <tr><th>Chq no</th><td><%= @bulk_transaction.chq_no %></td></tr>
       <tr><th>Bank acc</th><td> <%= @bulk_transaction.bank_acc %></td></tr>
       <tr><th>Beneficiary</th><td><%= @bulk_transaction.beneficiary %></td></tr>
       <tr><th>Notes</th><td> <%= @bulk_transaction.notes %></td></tr>
       <tr><th>Effective year</th><td><%= @bulk_transaction.effective_year %></td></tr>
       <tr><th>Effective months</th><td><%= @bulk_transaction.effective_months %></td></tr>
       </thead>
       </table>
       
       <%= hidden_field_tag(:bulk_transaction_id, @bulk_transaction.id) %>
</div>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Scholarships</h4></div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Student</th>
      <th>Sponsor</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Status</th>
      <th>Scholarship Amount(Rs.) </th>
      <th>Pay</th>
      <th>Amount Paid (Rs.) <%= text_field(:com, :amount_lkr, size:10 ) %></th>
      <th>Bank Date <%= text_field(:com, :bank_date, size:10)%></th>
      <th>Effective Year <%= text_field(:com, :effective_year, size:4)%></th>
      <th>Effective Month<%= text_field(:com, :effective_month, size:2)%></th>
      <th>Notes <%= text_field(:com, :notes, size:20)%></th>
     </tr>
   
  </thead>

  <tbody>
    <% @payment_details.each do |payment_detail| %>
    <%= fields_for 'payment_details[]', payment_detail do |p| %>
    	<% scholarship = payment_detail.scholarship %>
      <tr>
        <td><%= scholarship.student.full_name %></td>
        <td><%= scholarship.sponsor.full_name %></td>
        <td><%= scholarship.start_date %></td>
        <td><%= scholarship.end_date %></td>
        <td><%= scholarship.status %></td>
        <td><%= scholarship.amount %></td>
        <td><%= p.check_box :send_payment %></td>
        <td><%= p.text_field :amount_lkr ,"size" => 10 , class: "amount-lkr" %></td>
        <td><%= p.text_field :bank_date ,"size" => 10 , class: "bank-date" %></td>
        <td><%= p.text_field :effective_year ,"size" => 4 , class: "effective-year" %></td>
        <td><%= p.text_field :effective_month,"size" => 2, class: "effective-month" %></td>
         <td><%= p.text_field :notes , class: "notes" %></td>
         <%= p.hidden_field :schol_id %>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
    <div class="actions">
      <%= f.submit 'Create Payments', class: 'btn btn-primary' %>
    </div>
    
</div>

    

<% end %>


<%= link_to 'Show', @bulk_transaction %> |
<%= link_to 'Back', bulk_transactions_path %>

app/views/bulk_transactions/edit.html.erb
<h1>Editing Bulk Transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @bulk_transaction %> |
<%= link_to 'Back', bulk_transactions_path %>

app/views/bulk_transactions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Bulk Transactions</h1>
<%= link_to 'New Bulk transaction', new_bulk_transaction_path, class: "btn btn-primary" %>
<table class="table table-striped">
  <thead>
    <tr>
    	<th>Id</th>
      <th>Settled date</th>
      <th>Sender</th>
      <th>Amount</th>
      <th>Amount lkr</th>
      <th>Rate</th>
      <th>Bank date</th>
      <th>Chq no</th>
      <th>Bank acc</th>
      <th>Beneficiary</th>
      <th>Notes</th>
      <th>Effective year</th>
      <th>Effective months</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @bulk_transactions.sort_by{|x| x.bank_date}.reverse.each do |bulk_transaction| %>
      <tr>
      	<td><%= bulk_transaction.id %></td>
        <td><%= bulk_transaction.settled_date %></td>
        <td><%= bulk_transaction.sender %></td>
        <td><%= bulk_transaction.amount %></td>
        <td><%= bulk_transaction.amount_lkr %></td>
        <td><%= bulk_transaction.rate %></td>
        <td><%= bulk_transaction.bank_date %></td>
        <td><%= bulk_transaction.chq_no %></td>
        <td><%= bulk_transaction.bank_acc %></td>
        <td><%= bulk_transaction.beneficiary %></td>
        <td><%= bulk_transaction.notes %></td>
        <td><%= bulk_transaction.effective_year %></td>
        <td><%= bulk_transaction.effective_months %></td>
        <td><%= link_to 'View', bulk_transaction, class: "btn btn-info glyphicon glyphicon-info-sign" %></td>
        <td><%= link_to 'Edit', edit_bulk_transaction_path(bulk_transaction), class: "btn btn-warning glyphicon glyphicon-edit" %></td>
        <td><%= link_to 'Delete', bulk_transaction, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger glyphicon glyphicon-remove" %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/bulk_transactions/new.html.erb
<h1>New Bulk Transaction</h1>

<%= render 'form' %>


<%= link_to 'Back', bulk_transactions_path %>

app/views/bulk_transactions/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Settled date:</strong>
  <%= @bulk_transaction.settled_date %>
</p>

<p>
  <strong>Sender:</strong>
  <%= @bulk_transaction.sender %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @bulk_transaction.amount %>
</p>

<p>
  <strong>Amount lkr:</strong>
  <%= @bulk_transaction.amount_lkr %>
</p>

<p>
  <strong>Rate:</strong>
  <%= @bulk_transaction.rate %>
</p>

<p>
  <strong>Bank date:</strong>
  <%= @bulk_transaction.bank_date %>
</p>

<p>
  <strong>Chq no:</strong>
  <%= @bulk_transaction.chq_no %>
</p>

<p>
  <strong>Bank acc:</strong>
  <%= @bulk_transaction.bank_acc %>
</p>

<p>
  <strong>Beneficiary:</strong>
  <%= @bulk_transaction.beneficiary %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @bulk_transaction.notes %>
</p>

<p>
  <strong>Effective year:</strong>
  <%= @bulk_transaction.effective_year %>
</p>

<p>
  <strong>Effective months:</strong>
  <%= @bulk_transaction.effective_months %>
</p>

<%= link_to 'Add Payments',  addpayment_bulk_transaction_path(@bulk_transaction), method: :get,class: "btn btn-warning glyphicon glyphicon-edit" %> |
<%= link_to 'Edit', edit_bulk_transaction_path(@bulk_transaction) %> |
<%= link_to 'Back', bulk_transactions_path %>

<div class="panel panel-default">
  <div class="panel-heading"><h4>Payments to students </h4></div>
  <%= render partial: "payments/payment", locals: {pp:@bulk_transaction.payments} %>
</div>